### ISSUE TITLE
Метод containsGame возвращает false при добавлении одной игры

### ISSUE THREAD

**Issue by Gts-2022** [Gts-2022/javaqa-team-diplom#1]
# Описание
Метод containsGame возвращает false вместо true, если добавлена одна игра

# Локация дефекта 
https://github.com/Gts-2022/javaqa-team-diplom/blob/c8ac8cd9e9d807328a64226159b51948aae47351/src/main/java/ru/netology/GameStore.java#L32-L39

# Шаги воспроизведения

1.Открыть [код программы](https://github.com/Gts-2022/javaqa-team-diplom/blob/gamestore/src/test/java/ru/netology/GameStoreTest.java#L11-L20) и IDEA

2.Вырезать или закомментировать 4 и 5 тесты

3.Запустить [Тест 1](https://github.com/Gts-2022/javaqa-team-diplom/blob/gamestore/src/test/java/ru/netology/GameStoreTest.java#L11-L20) (shouldAddGame)

4.Посмотреть на вывод в консоли 

*Ожидаемый результат:* тест проходит

*Фактический результат:* тест падает (ошибка- **AssertionFailedError**)

# Скриншот
<img width="953" alt="Тест1" src="https://user-images.githubusercontent.com/121601578/227904386-a5044574-c8de-4720-b391-1bb9aaff2fa1.png">

# Окружение

* **Операционная система** Windows NT 10.0
* **IDE:** IntelliJ IDEA 2022.3.1 (Community Edition)
* **JAVA:** OpenJDK 11

**Comment by Aleks282** [comment]
# Метод shouldAddGame исправлен
[Код](https://github.com/Gts-2022/javaqa-team-diplom/blob/c8ac8cd9e9d807328a64226159b51948aae47351/src/test/java/ru/netology/GameStoreTest.java#L11-L20)
Тест 1 ( shouldAddGame ) проходит

![8](https://user-images.githubusercontent.com/121448171/229062909-2a3f4295-2b15-4d2b-9fb1-e917c1d9c415.jpg)
