### ISSUE TITLE
Метод sumGenre не суммирует жанр, если жанры игр разные

### ISSUE THREAD

**Issue by Aleks282** [Gts-2022/javaqa-team-diplom#10]
# Описание
Метод sumGenre не суммирует жанр, если жанры игр разные
# Локация дефекта
https://github.com/Gts-2022/javaqa-team-diplom/blob/8d107acf447ecd1a537bce80178539ad01dcc696/src/main/java/ru/netology/Player.java#L45-L55

# Шаги воспроизведения
1.Открыть [страницу с классом плеер](https://github.com/Aleks282/TeamDiplom/blob/b9b8232631a15d6b614545aa83bfdcf553e0ae77/src/test/java/ru/netology/PlayerTest.java#L39-L57) в IDEA

2.Запустить [Тест 3](https://github.com/Aleks282/TeamDiplom/blob/b9b8232631a15d6b614545aa83bfdcf553e0ae77/src/test/java/ru/netology/PlayerTest.java#L39-L57)(**shouldSumGenreIfGamesGenreDifferent**)

3.Посмотреть на вывод в консоли

*Ожидаемый результат:* тест проходит
*Фактический результат:* тест падает  (ошибка-  **AssertionFailedError**)

# Скриншот
![4](https://user-images.githubusercontent.com/121448171/228329738-38e104f2-1f42-46bc-ae00-4dede56a5166.jpg)

# Окружение 
* **Операционная система:** Windows 10 Домашняя
* **IDE:**  IntelliJ IDEA 2022.3.1 (Community Edition)
* **JAVA:**  OpenJDK 11

**Comment by Gts-2022** [comment]
# Метод sumGenre исправлен
[Код](https://github.com/Gts-2022/javaqa-team-diplom/blob/6f3d84d856a50e9ba94ad995c2863aa70812ceba/src/main/java/ru/netology/Player.java#L65-L77)
Тест 3 ( shouldSumGenreIfGamesGenreDifferent ) проходит
<img width="682" alt="Т2" src="https://user-images.githubusercontent.com/121601578/228896076-11519e3e-ad53-43b7-b460-d23512552b7f.png">
