### ISSUE TITLE
Метод sumGenre не суммирует жанр, от 0 и выше часов

### ISSUE THREAD

**Issue by Aleks282** [Gts-2022/javaqa-team-diplom#11]
# Описание
Метод sumGenre не суммирует жанр, от 0 и выше часов

# Локация дефекта
https://github.com/Gts-2022/javaqa-team-diplom/blob/8d107acf447ecd1a537bce80178539ad01dcc696/src/main/java/ru/netology/Player.java#L45-L55

# Шаги воспроизведения

1.Открыть [код программы](https://github.com/Aleks282/TeamDiplom/blob/b9b8232631a15d6b614545aa83bfdcf553e0ae77/src/test/java/ru/netology/PlayerTest.java#L59-L74) в IDEA

2.Запустить [Тест 4](https://github.com/Aleks282/TeamDiplom/blob/b9b8232631a15d6b614545aa83bfdcf553e0ae77/src/test/java/ru/netology/PlayerTest.java#L59-L74)(**shouldSumGenre0Hours**)

3.Посмотреть на вывод в консоли

*Ожидаемый результат:* тест проходит

*Фактический результат:* тест падает (ошибка- **AssertionFailedError**)

# Скриншот
![5](https://user-images.githubusercontent.com/121448171/228458126-f30cc5a2-b93e-46c3-a6aa-6017750199e4.jpg)

# Окружение 
* **Операционная система:** Windows 10 Домашняя
* **IDE:**  IntelliJ IDEA 2022.3.1 (Community Edition)
* **JAVA:**  OpenJDK 11

**Comment by Gts-2022** [comment]
# Метод sumGenre исправлен
[Код исправленный](https://github.com/Gts-2022/javaqa-team-diplom/blob/6f3d84d856a50e9ba94ad995c2863aa70812ceba/src/main/java/ru/netology/Player.java#L65-L77)
Тест 4 ( shouldSumGenre0Hours ) проходит
<img width="852" alt="Т4" src="https://user-images.githubusercontent.com/121601578/228897764-5726c1ca-4a14-497e-aa1e-d28619f3682c.png">
