### ISSUE TITLE
Метод sumGenre должен суммировать жанр, если две игры

### ISSUE THREAD

**Issue by Aleks282** [Gts-2022/javaqa-team-diplom#12]
# Описание
Метод sumGenre должен суммировать жанр, если две игры

# Локация дефекта
https://github.com/Gts-2022/javaqa-team-diplom/blob/8d107acf447ecd1a537bce80178539ad01dcc696/src/main/java/ru/netology/Player.java#L45-L55

# Шаги воспроизведения

1.Открыть [код программы](https://github.com/Aleks282/TeamDiplom/blob/b9b8232631a15d6b614545aa83bfdcf553e0ae77/src/test/java/ru/netology/PlayerTest.java#L22-L37) в IDEA

2.Запустить [Тест 2](https://github.com/Aleks282/TeamDiplom/blob/b9b8232631a15d6b614545aa83bfdcf553e0ae77/src/test/java/ru/netology/PlayerTest.java#L22-L37)(**shouldSumGenreIfTwoGames**)

3.Посмотреть на вывод в консоли

*Ожидаемый результат:* тест проходит

*Фактический результат:* тест падает (ошибка- **AssertionFailedError**)

# Скриншот
![1](https://user-images.githubusercontent.com/121448171/228465448-e6bc3c86-dcdb-4da7-a1c9-cac8fb402736.jpg)

# Окружение 
* **Операционная система:** Windows 10 Домашняя
* **IDE:**  IntelliJ IDEA 2022.3.1 (Community Edition)
* **JAVA:**  OpenJDK 11

**Comment by Gts-2022** [comment]
# Метод sumGenre исправлен
[Код исправленный](https://github.com/Gts-2022/javaqa-team-diplom/blob/6f3d84d856a50e9ba94ad995c2863aa70812ceba/src/main/java/ru/netology/Player.java#L65-L77)
Тест 2( **shouldSumGenreIfTwoGames** ) проходит
<img width="768" alt="Т2(0)" src="https://user-images.githubusercontent.com/121601578/228902538-a808ce2b-e888-49e6-a99d-a7966179019f.png">
