### ISSUE TITLE
Метод installGame должен суммировать часы, если игра установлена

### ISSUE THREAD

**Issue by Aleks282** [Gts-2022/javaqa-team-diplom#13]
# Описание
Метод installGame должен суммировать часы, если игра установлена

# Локация дефекта
https://github.com/Gts-2022/javaqa-team-diplom/blob/8d107acf447ecd1a537bce80178539ad01dcc696/src/main/java/ru/netology/Player.java#L24-L26

# Шаги воспроизведения

1.Открыть [код программы](https://github.com/Aleks282/TeamDiplom/blob/b9b8232631a15d6b614545aa83bfdcf553e0ae77/src/test/java/ru/netology/PlayerTest.java#L77-L88) в IDEA

2.Запустить [Тест 5](https://github.com/Aleks282/TeamDiplom/blob/b9b8232631a15d6b614545aa83bfdcf553e0ae77/src/test/java/ru/netology/PlayerTest.java#L77-L88)(**shouldSumHoursIfGameInstalled**)

3.Посмотреть на вывод в консоли

*Ожидаемый результат:* тест проходит

*Фактический результат:* тест падает (ошибка- **AssertionFailedError**)

# Скриншот
![2](https://user-images.githubusercontent.com/121448171/228468150-765578d7-e9a3-42e8-b524-e45260190f52.jpg)

# Окружение 
* **Операционная система:** Windows 10 Домашняя
* **IDE:**  IntelliJ IDEA 2022.3.1 (Community Edition)
* **JAVA:**  OpenJDK 11

**Comment by Gts-2022** [comment]
# Метод **installGame** исправлен

[Код исправленный](https://github.com/Gts-2022/javaqa-team-diplom/blob/6f3d84d856a50e9ba94ad995c2863aa70812ceba/src/main/java/ru/netology/Player.java#L31-L36)

Тест 5(**shouldSumHoursIfGameInstalled**) проходит
<img width="717" alt="Т5" src="https://user-images.githubusercontent.com/121601578/228904072-8c39a1b8-4c58-490c-9f23-b927b4bfb708.png">
