### ISSUE TITLE
Метод mostPlayerByGenre не возвращает самую популярную игру по жанру 1Жанр

### ISSUE THREAD

**Issue by Aleks282** [Gts-2022/javaqa-team-diplom#14]
# Описание
Метод mostPlayerByGenre должна вернуть самую популярную игру по жанру

# Локация дефекта
https://github.com/Gts-2022/javaqa-team-diplom/blob/8d107acf447ecd1a537bce80178539ad01dcc696/src/main/java/ru/netology/Player.java#L59-L61

# Шаги воспроизведения

1.Открыть [код программы](https://github.com/Aleks282/TeamDiplom/blob/b9b8232631a15d6b614545aa83bfdcf553e0ae77/src/test/java/ru/netology/PlayerTest.java#L90-L103) в IDEA

2.Запустить [Тест 6](https://github.com/Aleks282/TeamDiplom/blob/b9b8232631a15d6b614545aa83bfdcf553e0ae77/src/test/java/ru/netology/PlayerTest.java#L90-L103)(**shouldReturnMostPlayedGameByGenre1Genre**)

3.Посмотреть на вывод в консоли

*Ожидаемый результат:* тест проходит

*Фактический результат:* тест падает (ошибка- **AssertionFailedError**)

# Скриншот
![3](https://user-images.githubusercontent.com/121448171/228471669-f85277db-6154-430a-975d-ecc2a4a0cd52.jpg)

# Окружение 
* **Операционная система:** Windows 10 Домашняя
* **IDE:**  IntelliJ IDEA 2022.3.1 (Community Edition)
* **JAVA:**  OpenJDK 11

**Comment by Gts-2022** [comment]
# Метод **mostPlayerByGenre** исправлен
[Код исправленный](https://github.com/Gts-2022/javaqa-team-diplom/blob/6f3d84d856a50e9ba94ad995c2863aa70812ceba/src/main/java/ru/netology/Player.java#L84-L96)
Тест 6 (**shouldReturnMostPlayedGameByGenre1Genre**) проходит
<img width="795" alt="Т6" src="https://user-images.githubusercontent.com/121601578/228906661-1a7bce61-2f5b-46de-950c-59ae22793961.png">
