### ISSUE TITLE
Метод mostPlayerByGenre не возвращает самую популярную игру по жанру 2Жанр

### ISSUE THREAD

**Issue by Aleks282** [Gts-2022/javaqa-team-diplom#15]
# Описание
Метод mostPlayerByGenre должна вернуть самую популярную игру по жанру

# Локация дефекта
https://github.com/Gts-2022/javaqa-team-diplom/blob/8d107acf447ecd1a537bce80178539ad01dcc696/src/main/java/ru/netology/Player.java#L59-L61

# Шаги воспроизведения

1.Открыть [код программы](https://github.com/Aleks282/TeamDiplom/blob/b9b8232631a15d6b614545aa83bfdcf553e0ae77/src/test/java/ru/netology/PlayerTest.java#L105-L121) в IDEA

2.Запустить [Тест 7](https://github.com/Aleks282/TeamDiplom/blob/b9b8232631a15d6b614545aa83bfdcf553e0ae77/src/test/java/ru/netology/PlayerTest.java#L105-L121)(**shouldReturnMostPlayedGameByGenre2Genre**)

3.Посмотреть на вывод в консоли

*Ожидаемый результат:* тест проходит

*Фактический результат:* тест падает (ошибка- **AssertionFailedError**)

# Скриншот
![6](https://user-images.githubusercontent.com/121448171/228473132-0fb4cabd-5de4-450d-8177-d8905d5bb88f.jpg)

# Окружение 
* **Операционная система:** Windows 10 Домашняя
* **IDE:**  IntelliJ IDEA 2022.3.1 (Community Edition)
* **JAVA:**  OpenJDK 11

**Comment by Gts-2022** [comment]
# Метод mostPlayerByGenre исправлен
[Код исправленный](https://github.com/Gts-2022/javaqa-team-diplom/blob/6f3d84d856a50e9ba94ad995c2863aa70812ceba/src/main/java/ru/netology/Player.java#L84-L96)
Тест 7(**shouldReturnMostPlayedGameByGenre2Genre**) проходит
<img width="866" alt="Т7" src="https://user-images.githubusercontent.com/121601578/228912537-b30d6ff0-a013-4fc9-b99a-6b85a4ce4ea5.png">
