### ISSUE TITLE
Метод sumGenre не суммирует жанр игры, сыгранной дважды

### ISSUE THREAD

**Issue by Aleks282** [Gts-2022/javaqa-team-diplom#16]
# Описание
Метод sumGenre не суммирует жанр игры, сыгранной дважды

# Локация дефекта
https://github.com/Gts-2022/javaqa-team-diplom/blob/8d107acf447ecd1a537bce80178539ad01dcc696/src/main/java/ru/netology/Player.java#L45-L55

# Шаги воспроизведения

1.Открыть [код программы](https://github.com/Aleks282/TeamDiplom/blob/b9b8232631a15d6b614545aa83bfdcf553e0ae77/src/test/java/ru/netology/PlayerTest.java#L135-L148) в IDEA

2.Запустить [Тест 9](https://github.com/Aleks282/TeamDiplom/blob/b9b8232631a15d6b614545aa83bfdcf553e0ae77/src/test/java/ru/netology/PlayerTest.java#L135-L148)(**shouldSumGenreGamePlayedTwice**)

3.Посмотреть на вывод в консоли

*Ожидаемый результат:* тест проходит

*Фактический результат:* тест падает (ошибка- **AssertionFailedError**)

# Скриншот
![7](https://user-images.githubusercontent.com/121448171/228475367-40dc92b5-1f76-4190-bfec-11cddd8635bb.jpg)

# Окружение 
* **Операционная система:** Windows 10 Домашняя
* **IDE:**  IntelliJ IDEA 2022.3.1 (Community Edition)
* **JAVA:**  OpenJDK 11

**Comment by Gts-2022** [comment]
# Метод sumGenre исправлен
[Исправленный код](https://github.com/Gts-2022/javaqa-team-diplom/blob/6f3d84d856a50e9ba94ad995c2863aa70812ceba/src/main/java/ru/netology/Player.java#L65-L77)
Тест 8(**shouldSumGenreGamePlayedTwice**) проходит
<img width="762" alt="Т8" src="https://user-images.githubusercontent.com/121601578/228913969-d47f59ca-b558-47cc-97f5-c22b7d6ffaa4.png">
