### ISSUE TITLE
Метод containsGame не находит игру , которая была добавлена последней

### ISSUE THREAD

**Issue by Gts-2022** [Gts-2022/javaqa-team-diplom#2]
# Описание
Метод containsGame не находит последнюю добавленную игру, если было добавлено несколько игр
# Локация дефекта
https://github.com/Gts-2022/javaqa-team-diplom/blob/c8ac8cd9e9d807328a64226159b51948aae47351/src/main/java/ru/netology/GameStore.java#L32-L39

# Шаги воспроизведения
1.Открыть [код программы](https://github.com/Gts-2022/javaqa-team-diplom/blob/gamestore/src/test/java/ru/netology/GameStoreTest.java#L22-L31) в IDEA
.2.Вырезать или закомментировать 4 и 5 тесты
3.Запустить [Тест 2](https://github.com/Gts-2022/javaqa-team-diplom/blob/gamestore/src/test/java/ru/netology/GameStoreTest.java#L22-L31) (shouldFindLastAddGame)
4.Посмотреть на вывод в консоли

*Ожидаемый результат:* тест проходит
*Фактический результат:* тест падает  (ошибка-  **AssertionFailedError**)

# Скриншот

<img width="934" alt="Тест 2" src="https://user-images.githubusercontent.com/121601578/227917128-fde563f4-bc5b-4e9e-9e93-5ea0ec88a955.png">

# Окружение 
* **Операционная система:** Windows NT 10.0
* **IDE:**  IntelliJ IDEA 2022.3.1 (Community Edition)
* **JAVA:**  OpenJDK 11

**Comment by Aleks282** [comment]
# Метод shouldFindLastAddGame исправлен
[Код](https://github.com/Gts-2022/javaqa-team-diplom/blob/c8ac8cd9e9d807328a64226159b51948aae47351/src/test/java/ru/netology/GameStoreTest.java#L11-L20)
Тест 2 ( shouldAddGame ) проходит
![9](https://user-images.githubusercontent.com/121448171/229064142-94ad05c8-e849-4d27-a6c4-7e4c2c85feb5.jpg)
