### ISSUE TITLE
Метод containsGame возвращает false вместо true, если отсутствуют игры в каталоге

### ISSUE THREAD

**Issue by Gts-2022** [Gts-2022/javaqa-team-diplom#3]
# Описание
Метод containsGame возвращает false вместо true, если ни одной игры не добавлено в каталог

# Локация дефекта
https://github.com/Gts-2022/javaqa-team-diplom/blob/c8ac8cd9e9d807328a64226159b51948aae47351/src/main/java/ru/netology/GameStore.java#L32-L39

# Шаги воспроизведения

1.Открыть [код программы](https://github.com/Gts-2022/javaqa-team-diplom/blob/gamestore/src/test/java/ru/netology/GameStoreTest.java#L33-L38) в IDEA

2.Вырезать или закомментировать 4 и 5 тесты

3.Запустить [Тест 3](https://github.com/Gts-2022/javaqa-team-diplom/blob/gamestore/src/test/java/ru/netology/GameStoreTest.java#L33-L38) (**shouldFindValueInAbsenceOfGame**)

4.Посмотреть на вывод в консоли

*Ожидаемый результат:* тест проходит

*Фактический результат:* тест падает (ошибка- **AssertionFailedError**)

# Скриншот
<img width="903" alt="Тест 3" src="https://user-images.githubusercontent.com/121601578/227960471-baf9e669-bdce-414b-b28d-daa5c290dcfe.png">

# Окружение

**Операционная система:**  Windows NT 10.0
**IDE:**  IntelliJ IDEA 2022.3.1 (Community Edition)
**JAVA:** OpenJDK 11

**Comment by Aleks282** [comment]
# Метод containsGame исправлен
[Код](https://github.com/Aleks282/TeamDiplom/blob/a46b227feb8463ab452e3b35afba8b3a94bdb968/src/test/java/ru/netology/GameStoreTest.java#L33-L38)
Тест 3 ( shouldFindLastAddGame ) проходит
![10](https://user-images.githubusercontent.com/121448171/229091658-5fb82a4a-1335-4510-a07a-749f0047de4c.jpg)
