### ISSUE TITLE
Метод getSumPlayedTime не находит общее количество времени всех игроков каталога

### ISSUE THREAD

**Issue by Gts-2022** [Gts-2022/javaqa-team-diplom#4]
# Описание
Метод **getSumPlayedTime**  не находит общее количество времени всех игроков, проведённого за играми этого каталога. (Выдает **0**.)

# Локация дефекта
https://github.com/Gts-2022/javaqa-team-diplom/blob/c8ac8cd9e9d807328a64226159b51948aae47351/src/main/java/ru/netology/GameStore.java#L75-L77

# Шаги воспроизведения

1.Открыть [код программы](https://github.com/Gts-2022/javaqa-team-diplom/blob/gamestore/src/test/java/ru/netology/GameStoreTest.java#L110-L131) в IDEA

2.Вырезать или закомментировать 4 и 5 тесты

3.Запустить [Тест 8](https://github.com/Gts-2022/javaqa-team-diplom/blob/gamestore/src/test/java/ru/netology/GameStoreTest.java#L110-L131) (**shouldFindTotalAmountTimeAllPlayersSpentPlayingGamesInCatalog**)

4.Посмотреть на вывод в консоли

*Ожидаемый результат:* тест проходит

*Фактический результат:* тест падает (ошибка- **AssertionFailedError**)

# Скриншот
<img width="936" alt="Тест 8" src="https://user-images.githubusercontent.com/121601578/227967860-cc57d95d-16ba-419a-b816-3c1763a5f9c4.png">

# Окружение

**Операционная система:** Windows NT 10.0
**IDE:** IntelliJ IDEA 2022.3.1 (Community Edition)
**JAVA:** OpenJDK 11

**Comment by Aleks282** [comment]
# Метод getSumPlayedTime исправлен
[Код](https://github.com/Aleks282/TeamDiplom/blob/a46b227feb8463ab452e3b35afba8b3a94bdb968/src/test/java/ru/netology/GameStoreTest.java#L33-L38)
Тест 8 ( shouldFindTotalAmountTimeAllPlayersSpentPlayingGamesInCatalog ) проходит
 
![11](https://user-images.githubusercontent.com/121448171/229092539-b751c198-e83a-4a5e-bdd9-6fd545bf6595.jpg)
