### ISSUE TITLE
 Метод addPlayTime  не находит  время, потраченного игроком на определенную игру

### ISSUE THREAD

**Issue by Gts-2022** [Gts-2022/javaqa-team-diplom#5]
# Описание 
 Метод **addPlayTime**   в классе GameStoreTest не находит  общее количество времени, которое потратил игрок "Super" на  игру "Нетология2".
# Локация дефекта
https://github.com/Gts-2022/javaqa-team-diplom/blob/c8ac8cd9e9d807328a64226159b51948aae47351/src/main/java/ru/netology/GameStore.java#L46-L52

# Шаги воспроизведения

1.Открыть [код программы](https://github.com/Gts-2022/javaqa-team-diplom/blob/gamestore/src/main/java/ru/netology/GameStore.java#L46-L52) в IDEA.

2.Запустить [Тест 4](https://github.com/Gts-2022/javaqa-team-diplom/blob/gamestore/src/test/java/ru/netology/GameStoreTest.java#L40-L54) (**shouldFindTotalAmountTimePlayerSpentOnCertainGame**)

3.Посмотреть на вывод в консоли.

*Ожидаемый результат:* тест проходит.

*Фактический результат:* тест падает с ошибкой -**incompatible types: void cannot be converted to java.lang.Integer**.

#Скриншот 
<img width="938" alt="Тест 4" src="https://user-images.githubusercontent.com/121601578/228002053-8f5d212c-6c2b-41d8-ac4d-f6c8d0d28bb1.png">

# Окружение

**Операционная система:** Windows NT 10.0
**IDE:** IntelliJ IDEA 2022.3.1 (Community Edition)
**JAVA:** OpenJDK 11

**Comment by Aleks282** [comment]
# Метод addPlayTime исправлен
[Код](https://github.com/Aleks282/TeamDiplom/blob/a46b227feb8463ab452e3b35afba8b3a94bdb968/src/test/java/ru/netology/GameStoreTest.java#L40-L54)
Тест 4 ( shouldFindTotalAmountTimePlayerSpentOnCertainGame ) проходит
 
![12](https://user-images.githubusercontent.com/121448171/229093642-47664a14-4c0d-47a7-a750-93f0fe659cf8.jpg)
