### ISSUE TITLE
Метод addPlayTime в 5 тесте не находит количество времени

### ISSUE THREAD

**Issue by Gts-2022** [Gts-2022/javaqa-team-diplom#6]
# Описание 
 Метод **addPlayTime**   в классе GameStoreTest не находит   количество времени, если в каталоге никто не играл
# Локация дефекта
https://github.com/Gts-2022/javaqa-team-diplom/blob/c8ac8cd9e9d807328a64226159b51948aae47351/src/main/java/ru/netology/GameStore.java#L46-L52

# Шаги воспроизведения

1.Открыть [код программы](https://github.com/Gts-2022/javaqa-team-diplom/blob/gamestore/src/main/java/ru/netology/GameStore.java#L46-L52) в IDEA.

2.Запустить [Тест 5](https://github.com/Gts-2022/javaqa-team-diplom/blob/c8ac8cd9e9d807328a64226159b51948aae47351/src/test/java/ru/netology/GameStoreTest.java#L56-L63) (**findAmountOfTimeIfNoOnePlayedInCatalog**)

3.Посмотреть на вывод в консоли.

*Ожидаемый результат:* тест проходит.

*Фактический результат:* тест падает с ошибкой -**incompatible types: void cannot be converted to java.lang.Integer**.

# Скриншот 
<img width="919" alt="Тест 5" src="https://user-images.githubusercontent.com/121601578/228007142-c31989fb-57df-4fdd-9935-92858f66fda0.png">

# Окружение

**Операционная система:** Windows NT 10.0
**IDE:** IntelliJ IDEA 2022.3.1 (Community Edition)
**JAVA:** OpenJDK 11

**Comment by Aleks282** [comment]
# Метод addPlayTime исправлен
[Код](https://github.com/Aleks282/TeamDiplom/blob/a46b227feb8463ab452e3b35afba8b3a94bdb968/src/test/java/ru/netology/GameStoreTest.java#L40-L54)
Тест 5 ( findAmountOfTimeIfNoOnePlayedInCatalog ) проходит
 
 
![13](https://user-images.githubusercontent.com/121448171/229094560-581c2ced-c377-41c8-ba9a-ba79c8026629.jpg)
