### ISSUE TITLE
Метод shouldSumGenreIfOneGame не суммирует жанр, если одна игра

### ISSUE THREAD

**Issue by Aleks282** [Gts-2022/javaqa-team-diplom#9]
# Описание
Метод sumGenre не суммирует жанр, если одна игра
# Локация дефекта
https://github.com/Gts-2022/javaqa-team-diplom/blob/8d107acf447ecd1a537bce80178539ad01dcc696/src/main/java/ru/netology/Player.java#L45-L55

# Шаги воспроизведения
1.Открыть [страницу с классом плеер](https://github.com/Aleks282/TeamDiplom/blob/b9b8232631a15d6b614545aa83bfdcf553e0ae77/src/test/java/ru/netology/PlayerTest.java#L8-L20) в IDEA

2.Запустить [Тест 1](https://github.com/Aleks282/TeamDiplom/blob/b9b8232631a15d6b614545aa83bfdcf553e0ae77/src/test/java/ru/netology/PlayerTest.java#L8-L20)(**shouldSumGenreIfOneGame**)

3.Посмотреть на вывод в консоли 

*Ожидаемый результат:* тест проходит

*Фактический результат:* тест падает (ошибка- **AssertionFailedError**)

# Скриншот
![3](https://user-images.githubusercontent.com/121448171/228327269-a169e7b3-80f3-43bb-a48f-9a3bbee25987.jpg)

# Окружение 
* **Операционная система:** Windows 10 Домашняя
* **IDE:**  IntelliJ IDEA 2022.3.1 (Community Edition)
* **JAVA:**  OpenJDK 11

**Comment by Gts-2022** [comment]
# Описание
[Код исправлен](https://github.com/Gts-2022/javaqa-team-diplom/blob/6f3d84d856a50e9ba94ad995c2863aa70812ceba/src/main/java/ru/netology/Player.java#L65-L77)
Тест 1 ( shouldSumGenreIfOneGame ) проходит

<img width="819" alt="Т11" src="https://user-images.githubusercontent.com/121601578/230307604-0b4f6e55-d123-4c44-ab2c-827626232257.png">
